# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     SponsorDotDog.Repo.insert!(%SponsorDotDog.SomeModel{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Alabama", state_abbreviation: "AL", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Alaska", state_abbreviation: "AK", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Arizona", state_abbreviation: "AZ", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Arkansas", state_abbreviation: "AR", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "California", state_abbreviation: "CA", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Colorado", state_abbreviation: "CO", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Connecticut", state_abbreviation: "CT", state_group: 4})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Delaware", state_abbreviation: "DE", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Florida", state_abbreviation: "FL", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Georgia", state_abbreviation: "GA", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Hawaii", state_abbreviation: "HI", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Idaho", state_abbreviation: "ID", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Illinois", state_abbreviation: "IL", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Indiana", state_abbreviation: "IN", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Iowa", state_abbreviation: "IA", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Kansas", state_abbreviation: "KS", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Kentucky", state_abbreviation: "KY", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Louisiana", state_abbreviation: "LA", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Maine", state_abbreviation: "ME", state_group: 4})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Maryland", state_abbreviation: "MD", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Massachusetts", state_abbreviation: "MA", state_group: 4})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Michigan", state_abbreviation: "MI", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Minnesota", state_abbreviation: "MN", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Mississippi", state_abbreviation: "MS", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Missouri", state_abbreviation: "MO", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Montana", state_abbreviation: "MT", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Nebraska", state_abbreviation: "NE", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Nevada", state_abbreviation: "NV", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "New Hampshire", state_abbreviation: "NH", state_group: 4})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "New Jersey", state_abbreviation: "NJ", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "New Mexico", state_abbreviation: "NM", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "New York", state_abbreviation: "NY", state_group: 4})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "North Carolina", state_abbreviation: "NC", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "North Dakota", state_abbreviation: "ND", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Ohio", state_abbreviation: "OH", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Oklahoma", state_abbreviation: "OK", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Oregon", state_abbreviation: "OR", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Pennsylvania", state_abbreviation: "PA", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Rhode Island", state_abbreviation: "RI", state_group: 4})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "South Carolina", state_abbreviation: "SC", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "South Dakota", state_abbreviation: "SD", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Tennessee", state_abbreviation: "TN", state_group: 5})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Texas", state_abbreviation: "TX", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Utah", state_abbreviation: "UT", state_group: 2})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Vermont", state_abbreviation: "VT", state_group: 4})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Virginia", state_abbreviation: "VA", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Washington", state_abbreviation: "WA", state_group: 1})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "West Virginia", state_abbreviation: "WV", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Wisconsin", state_abbreviation: "WI", state_group: 3})
SponsorDotDog.Repo.insert!(%SponsorDotDog.State{state_name: "Wyoming", state_abbreviation: "WY", state_group: 2})
